GoodSide.Web/Models/POS/OtheInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoodSide.Web.Models.POS
{
    public class OtheInfoViewModel
    {
        [Required]
        public string defaultcurrency { get; set; }
        public string currencyname { get; set; }
        public string currencysymbol { get; set; }

        [Required]
        [Display(Name="Sales Person")]
        public string salespersonid { get; set; }

        public string salesperson { get; set; }

        public string DestinationPoint { get; set; }

        public string PassWord { get; set; }

        public string OptiontoShow { get; set; }

        public SelectList CurrencyList { get; set; }

        public SelectList SalesPersonList { get; set; }

        public SelectList DestinationPointList { get; set; }

        public string changeSalesPersonMessage { get; set; }

    }
}

GoodSide.Web/Models/POS/ProductSearchViewModel.cs
using GoodSide.Domain.Entities;
using GoodSide.Web.Models.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoodSide.Web.Models.POS
{



    public class ProductSearchViewModel
    {
        public string id { get; set; }
        public string pno { get; set; }
        public string pname { get; set; }
        public string description { get; set; }
        public string barcode_no { get; set; }
        public string supplier { get; set; }
        public string supplierid { get; set; }
        public string typeid { get; set; }
        public string categoryid { get; set; }
        public string stockTypeid { get; set; }
        public int companyid { get; set; }
        public string price { get; set; }
        public string quantity { get; set; }
        public string discount { get; set; }
        public string stype { get; set; }
        public string allocatedS { get; set; }
        public string unallocatedS { get; set; }
        public string totaS { get; set; }
        public int locationid { get; set; }

        public SelectList Suppliers { get; set; }
        public SelectList Categories { get; set; }
        public SelectList StockTypes { get; set; }
        public SelectList ProductTypes { get; set; }

       

    }

    public class ProductSearchDataTableData : DataTableModel
    {
        public List<ProductSearchItemInfo> data { get; set; }
    }




}

GoodSide.Web/Models/POS/ReportConfig.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GoodSide.Web.Models.POS
{

    public class GetReportModel
    {
        public List<ReportItem> reportsList { get; set; }
    }

    public class ReportItem
    {
        public string Name { get; set; }
        public string Displayname { get; set; }
        public string DefaultValue { get; set; }
        public bool Selected { get; set; }
    }
}

GoodSide.Web/Controllers/POSController.cs
using GoodSide.Web.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GoodSide.Domain.Services;
using GoodSide.Web.Models.Common;
using GoodSide.Web.Models.POS;
using System.Net.Http;
using System.Net;
using AutoMapper;
using Newtonsoft.Json;
using GoodSide.Web.Models.Customer;
using GoodSide.Domain.Helpers;
using System.ComponentModel;
using System.Reflection;
using System.Xml.Serialization;
using System.IO;


namespace GoodSide.Web.Controllers
{
    public class POSController : BaseController
    {
        // GET: POS
        private IProductSearchService _productSearchService;
        private IOrderDetailService _orderDetailService;
        private IKeyValueItemService _keyValueItemService;
        private IAvailableQuantityService _availableQuantityService;
        private IProductService _productService;
        private IPOSService _posService;
        private IOrderMasterService _OrderMasterService;

        public POSController(IProductSearchService productSearchService, IOrderDetailService orderDetailService, IKeyValueItemService keyValueItemService, IAvailableQuantityService availableQuantityService, IProductService productService, IPOSService posService, IOrderMasterService OrderMasterService)
        {
            _productSearchService = productSearchService;
            _orderDetailService = orderDetailService;
            _keyValueItemService = keyValueItemService;
            _availableQuantityService = availableQuantityService;
            _productService = productService;
            _posService = posService;
            _OrderMasterService = OrderMasterService;
        }

        public ActionResult Index()
        {
            var datev = DateTime.Now.ToString("yyyyMMdd");

            var OrdStatus = 0;
            if (ClientSession.GetSession(SessionConstants.POSOrderMaster) != null)
            {
                var ordMaster = (OrderMaster)ClientSession.GetSession(SessionConstants.POSOrderMaster);
                OrdStatus = ordMaster.orderstatus;
            }
            ClientSession.SetSession(SessionConstants.orderstatus, OrdStatus);
            ViewBag.Ordstatus = OrdStatus;
            return View();
        }

        public PartialViewResult ProductDisplay(string items)
        {
            var ordersummary = new ProductDetailSummaryModel();
            var lstItems = new List<OrderDetail>();
            var sessionObj = ClientSession.GetSession(SessionConstants.POSSelectedProducts);
            if (sessionObj != null)
            {
                var sessionitems = ((List<OrderDetail>)sessionObj).ToList();
                lstItems = sessionitems.GroupBy(x => new { x.pid, x.uniqueid }).Select(x => new OrderDetail()
                {
                    pid = x.First().pid,
                    SKU = x.First().SKU,
                    productname = x.First().productname,
                    qty = x.Sum(y => y.qty),
                    slprice = x.First().slprice,
                    slprice_base = x.First().slprice_base,
                    discgiven_base = x.Sum(y => y.discgiven_base),
                    discgiven = x.Sum(y => y.discgiven),
                    netprice = ((x.Sum(y => y.qty) * x.First().slprice) - x.Sum(y => y.discgiven)),
                    vatamount = x.Sum(y => y.vatamount),
                    productdesc = x.First().productdesc,
                    deliverytype = x.First().deliverytype,
                    deliverydate = x.First().deliverydate,
                    promotion = x.First().promotion,
                    uniqueid = x.First().uniqueid

                }).ToList();
            }
            ordersummary.orderdetailList = lstItems;
            var ordermasterSession = ClientSession.GetSession(SessionConstants.POSOrderMaster);
            if (ordermasterSession != null)
            {
                ordersummary.orderMaster = (OrderMaster)ordermasterSession;
            }
            else
            {
                ordersummary.orderMaster = (new OrderMaster());
            }
            ordersummary.BIRTReportURL = CommonMethods.BIRTReportUrl();
            return PartialView(ordersummary);
        }

        public ActionResult ProductDisplayPopup()
        {
            return PartialView();
        }

        public JsonResult GetProductSearchData(int draw, int start, int length)
        {
            //var Searchhistory = ClientSession.GetSession(SessionConstants.Searchhistory);
            //if (Searchhistory != null)
            //{
            //    string[] searchP = Convert.ToString(Searchhistory).Split(',');
            //    draw = (Convert.ToInt32(searchP[0]) > draw) ? Convert.ToInt32(searchP[0]) : draw;
            //    start = (Convert.ToInt32(searchP[1]) > start) ? Convert.ToInt32(searchP[1]) : start;
            //    length = (Convert.ToInt32(searchP[2]) > length) ? Convert.ToInt32(searchP[2]) : length;
            //}            
            var pname = HttpContext.Request.QueryString["pname"];
            var description = HttpContext.Request.QueryString["description"];
            var pno = HttpContext.Request.QueryString["pno"];
            var barcode_no = HttpContext.Request.QueryString["barcode_no"];
            var supplierid = HttpContext.Request.QueryString["supplierid"];
            var typeid = HttpContext.Request.QueryString["typeid"];
            var categoryid = HttpContext.Request.QueryString["categoryid"];
            var stockTypeid = HttpContext.Request.QueryString["stockTypeid"];

            int sortColumn = -1;
            string sortDirection = "asc";

            if (HttpContext.Request.QueryString["order[0][column]"] != null)
            {
                sortColumn = int.Parse(HttpContext.Request.QueryString["order[0][column]"]);
            }
            if (HttpContext.Request.QueryString["order[0][dir]"] != null)
            {
                sortDirection = HttpContext.Request.QueryString["order[0][dir]"];
            }

            var lstProperties = typeof(ProductSearchViewModel).GetProperties().ToList();

            var data = _productSearchService.GetAll(pname, description, pno, barcode_no, supplierid, typeid, categoryid, stockTypeid, start, length, lstProperties[sortColumn].Name, sortDirection);

            ProductSearchDataTableData dataTableData = new ProductSearchDataTableData();
            dataTableData.recordsTotal = data.pagingInfo.FirstOrDefault().total;
            dataTableData.data = data.productSearchItemInfo;
            dataTableData.recordsFiltered = data.pagingInfo.FirstOrDefault().total;
            var history = string.Concat(Convert.ToString(draw), ',', Convert.ToString(start), ',', Convert.ToString(length));
            ClientSession.SetSession(SessionConstants.Searchhistory, history);
            return Json(dataTableData, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult _ProductInfo(string pid, string uniqueId)
        {
            if (pid == "0")
            {
                return PartialView(new OrderDetail());
            }
            var sessionObj = ClientSession.GetSession(SessionConstants.POSSelectedProducts);
            if (sessionObj != null)
            {
                //GroupBy(x => new { x.pid, x.uniqueid })
                var product = ((List<OrderDetail>)sessionObj).Where(x => x.pid == pid && x.uniqueid == int.Parse(uniqueId)).GroupBy(x => new { x.pid, x.uniqueid }).Select(x => new OrderDetail()
                {
                    pid = x.Key.pid,
                    productname = x.First().productname,
                    productdesc = x.First().productdesc,
                    slprice = x.First().slprice,
                    qty = x.Sum(y => y.qty),
                    discgiven = x.Sum(y => y.discgiven),
                    colors = x.First().colors,
                    vatamount = x.Sum(y => y.vatamount),
                    uniqueid = x.Key.uniqueid


                }).FirstOrDefault();

                if (ClientSession.GetSession(SessionConstants.POSOrderMaster) != null)
                {
                    var orderMaster = (OrderMaster)ClientSession.GetSession(SessionConstants.POSOrderMaster);
                    if (orderMaster != null)
                    {
                        product.currency_symbol = orderMaster.currency_symbol;
                    }
                }

                return PartialView(product);
            }
            return PartialView(new OrderDetail());
        }

        public JsonResult _EditProductInfo(string pid, string uniqueId)
        {
            var sessionObj = ClientSession.GetSession(SessionConstants.POSSelectedProducts);
            var product = ((List<OrderDetail>)sessionObj).Where(x => x.pid == pid && x.uniqueid == int.Parse(uniqueId)).GroupBy(x => new { x.pid, x.uniqueid }).Select(x => new OrderDetail()
            {
                pid = x.Key.pid,
                productname = x.First().productname,
                productdesc = x.First().productdesc,
                slprice = x.First().slprice,
                qty = x.Sum(y => y.qty),
                discgiven = x.Sum(y => y.discgiven),
                colors = x.First().colors,
                vatamount = x.Sum(y => y.vatamount),
                uniqueid = x.Key.uniqueid,
                stype = x.First().stype,
                sale_type = x.First().sale_type,
                cust_leadtime = x.First().cust_leadtime,
                Discount_Comment = x.First().Discount_Comment
            }).FirstOrDefault();

            if (ClientSession.GetSession(SessionConstants.POSOrderMaster) != null)
            {
                var orderMaster = (OrderMaster)ClientSession.GetSession(SessionConstants.POSOrderMaster);

GoodSide.Web/Views/POS/Discount.cshtml
@model GoodSide.Web.Models.POS.DiscountModel


@using (Html.BeginForm("ApplyDiscount", "Customer", FormMethod.Post, new { id = "frnDiscount" }))
{
    @Html.HiddenFor(x => x.SelectedPrductIds)
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                @Html.RadioButtonFor(model => model.DiscountTypeID, "1", new { Checked = "checked", id = "discountfixedamount" })
                <label for="discountfixedamount">Fixed Amount</label>
                @Html.RadioButtonFor(model => model.DiscountTypeID, "2", new { id = "discountpercentage" })
                <label for="discountpercentage">In Percentage</label>

            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                <label>Discount</label>
                <span>@Html.TextBoxFor(model => model.Discount, new { @class = "form-control numericbox", @maxlength = "10", autocomplete = "off" })</span>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="form-group">
                <label for="exampleInputEmail1">Comments</label>
                <span> @Html.TextBoxFor(model => model.Discount_Comment, new { @class = "form-control text-left", maxlength = "255", autocomplete = "off" })</span>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="form-group">
                <label for="exampleInputEmail1">Password</label>
                @Html.PasswordFor(m => m.Password, new { @class = "form-control", maxlength = "50", autocomplete = "off" })
            </div>
        </div>
    </div>

    <div class="row" id="divApplydiscount">
        <div class="col-sm-12">
            <div class="pull-right">
                <button class="btn btn-success" type="submit">Apply Discount</button>
                <button class="btn btn-default" type="reset" id="btnClearDiscount">Clear</button>
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true" type="button"> Cancel</button>
            </div>
        </div>

    </div>

}
<script>
    $(document).ready(function(){
        var status = @ViewBag.OrdStatus;

        if(status == 6)
        {
            $("#divApplydiscount :input").attr("disabled", true);
        }
    });

    $(function () {
        $(".numericbox").keydown(function (e) {
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                // Allow: Ctrl+A, Command+A
               (e.keyCode == 65 && (e.ctrlKey === true || e.metaKey === true)) ||
                // Allow: home, end, left, right, down, up
               (e.keyCode >= 35 && e.keyCode <= 40)) {
                // let it happen, don't do anything
                return;
            }
            // Ensure that it is a number and stop the keypress
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });

        $('#frnDiscount').submit(function (e) {
            var form = $(this);
            if (form.validate().form()) {
                $.post('@Url.Action("ApplyDiscount", "Customer")',
                    form.serialize(),
                    function (data) {
                        if (data.success) {
                            $.each(BootstrapDialog.dialogs, function (id, dialog) {
                                if (id === "dialogDiscount") {
                                    dialog.close();
                                }
                            });
                            loadOrderMainGrid();
                        }
                        else {
                            if (data.message != null)
                                BootstrapDialog.alert(data.message);
                        }
                    }
                );
            }
            e.preventDefault();
        });

        $('#btnClearDiscount').on('click', function () {
            $("#Discount").val(0);
            $("#frnDiscount").submit();
        });

    });




</script>

GoodSide.Web/Views/POS/_GetReport.cshtml
@model List<GoodSide.Web.Models.POS.ReportItem>
@using (Ajax.BeginForm("SelectReport", "POS", new AjaxOptions { OnBegin = "AjaxRequestStart();", OnComplete = "AjaxRequestFinish();", HttpMethod = "Post", OnSuccess = "SelectReportCompleted" }, new { enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                @*<label class="control-label">Select Report</label>
                    <span>@Html.DropDownListFor(model => model.Report, ((List<string>)ViewBag.Reports).Select(m => new SelectListItem { Text = m, Value = m}), new { @id = "ddlReport", @class = "form-control" })</span>*@
                <div class="table-responsive">
                    <table id="tblProductDisplay" class="table table-hover table-bordered">
                        <thead>
                            <tr>                               
                                @*@Html.CheckBoxFor(m => m.isOrderChecked, new { @id = "isOrderChecked" })*@
                                <th><input id="ckSelectAll" style="text-align:center !important " type="checkbox" class="checkbox" /></th>
                                <th>Report</th>
                                @*<th hidden="hidden">Reportname</th>*@
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < Model.Count; i++)
                            {
                                <tr>

                                    <td class="center-block">
                                        @Html.CheckBoxFor(x => @Model[i].Selected, new { @name = @Model[i].Name })
                                        @Html.HiddenFor(x => @Model[i].Name)

                                    <td>@Model[i].Displayname</td>

                                </tr>
                            }
                            

                            @*@foreach (var item in Model)
                            {
                                <tr>

                                    <td class="center-block">
                                        @Html.EditorFor(item.Name)
                                       <td>@item.Displayname</td>

                                </tr>
                            }*@
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="pull-right">
                <button class="btn btn-success" type="submit">Open Report</button>
                <button class="btn btn-default" data-dismiss="modal" onclick="closeopendialog()" aria-hidden="true" type="button"> Cancel</button>
            </div>
        </div>
    </div>

}
<script>

    $(document).ready(function () {
        //alert('test');
        //$(".bootstrap-dialog-close-button", $(this).parent()).hide();
        //$(".close").css('display', 'none')
        //$("#reportoptiondialog").dialog({
        //    closeOnEscape: false,
        //    open: function (event, ui) {
        //        //$(".close").css('display', 'none')
        //        $(".ui-dialog-titlebar-close", ui.dialog | ui).hide();
        //    }
        //});
        $('#reportoptiondialog').find('.close').remove();

    });

    function SelectReportCompleted(result) {
      
        if (result.success) {
            if (result.reportnames != '') {
                //BootstrapDialog.alert(result.message, function () {
                $.each(BootstrapDialog.dialogs, function (id, dialog) {
                    if (id === "reportoptiondialog") {
                        dialog.close();
                    }
                });
                // });
                DisplayReport(result.reportnames);
            }
            else
            {
               BootstrapDialog.alert("Please select At least one report");
            }
        }
        else {
            var Message = "Error in Open Report" + result.reportnames;
            BootstrapDialog.alert(Message);
        }
    }
    function closeopendialog() {

        $.each(BootstrapDialog.dialogs, function (id, dialog) {
            if (id === "reportoptiondialog") {
                dialog.close();
            }
            if (id === "dialogOrderSummary") {
                dialog.close();
            }
            if (id === "dialogPaymentInfo") {
                dialog.close();

                var partialViewUrl = "@string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~/Customer/_ChangeSalesPerson"))";
                POSJS.dialogCustomerInstance = POSJS.LoadDialogueBox(partialViewUrl, 'dialogChangeSalesPerson', 'Change SalesPerson');

                var urlAction = "@string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"))Customer/CreateNewOrder"
                var result = POSJS.CreateNewOrder(urlAction);

                @*window.location.reload(true);
                window.location.href = '@Url.Action("Index", "POS")';*@
            }
        });

    }
</script>


GoodSide.Web/Views/POS/_OtherInfo.cshtml
@model GoodSide.Web.Models.POS.OtheInfoViewModel


<div class="table-responsive">
    <table class="table table-bordered">
        <tr>
            <td class="control-label">Currency</td>
            <td>@Model.currencysymbol @Model.currencyname</td>
        </tr>

        <tr>
            <td class="control-label">Sales Person
            <td>@Model.salesperson</td>
        </tr>       
</div>
    </table>
</div>


<div class="btnrow">
    <a href="#" class="linkbtn" onclick="UpdateOtherInfo()"><img src="~/POSContent/images/ic-edit.png" alt="" />Modify</a>
</div>

<script>

    function UpdateOtherInfo() {
        var partialViewUrl = "@string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~/POS/_OtherInfoUpdate"))";
        POSJS.dialogCustomerInstance = POSJS.LoadDialogueBox(partialViewUrl, 'dialogUpdateOtherInfo', 'Update Other Information');
    }

</script>

GoodSide.Web/Views/POS/_OtherInfoUpdate.cshtml
@model GoodSide.Web.Models.POS.OtheInfoViewModel

@using (Html.BeginForm("_OtherInfoUpdate", "POS", FormMethod.Post, new { id = "frmOtherInfoUpdate" }))
{
    @*<div class="row">
        <div class="col-sm-3">
            <label class="control-label">Currency</label>
        </div>
        <div class="col-sm-4">
            @Html.DropDownListFor(m => m.defaultcurrency, Model.CurrencyList, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.defaultcurrency)
        </div>
    </div>*@
    <div class="row">
        <div class="col-sm-3">
            <label class="control-label">Sales Person</label>
        </div>
        <div class="col-sm-4">
            @Html.DropDownListFor(m => m.salespersonid, Model.SalesPersonList, "-- Select Sales Person --", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.salespersonid)
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="pull-right">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true" type="button"> Cancel</button>
                <button class="btn btn-success" type="submit">Update</button>
            </div>
        </div>

    </div>

}

<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script>
    $(function () {
        $('#frmOtherInfoUpdate').submit(function (e) {          
            if ($('#frmOtherInfoUpdate').validate().valid()) {
                var partialViewUrl = "@string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~/POS/_OtherInfoUpdate"))";
                $.ajax({
                    url: partialViewUrl,
                    type: "POST",
                    data: $(this).serialize(),
                    success: function (data) {
                        $.each(BootstrapDialog.dialogs, function (id, dialog) {
                            if (id === "dialogUpdateOtherInfo") {
                                dialog.close();
                            }
                            var actionURL = "@string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~/POS/_OtherInfo"))";
                            POSJS.UpdateOtherInfo(actionURL, 'dvOtherInfo');

                            var SourceType = data.requestedsourcetype; 
                            if (SourceType == 'payment') {

                                var partialViewUrl = "@string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~/Customer/PaymentInfo"))";
                                var paymentinfodialog = POSJS.LoadDialogueBox(partialViewUrl, 'dialogPaymentInfo', 'POS', null);
                            }
                            else if (SourceType == 'quote')
                            {
                                var urlActionSave = "@string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"))Customer/SaveOrderAsQuote"

                                    var resultData = POSJS.SaveOrderAsQuote(urlActionSave);

                                if (resultData.success == true) {
                    
                                    var reporturl = $("#hdnReportBIRTURL").val().replace("{orderid}", resultData.orderId);
                                    window.open(reporturl, '_blank', "height=1000,width=800");

                                    BootstrapDialog.alert(resultData.message, function () {
                                        $.each(BootstrapDialog.dialogs, function (id, dialog) {
                                            if (id === "dialogPaymentInfo") {
                                                dialog.close();
                                            }
                                        });
                                        CreateNewOrder();
                                    });

                                    //alert("Quote Saved Successfully");
                                    //CreateNewOrder();
                                }
                                else {
                                    alert(resultData.message);
                                }
                            }

                        });
                    }
                });
            }
            e.preventDefault();
        });
      
    });
</script>