GoodSide.Web/Models/StockDetail/StockDetailImageViewModel.cs
using GoodSide.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GoodSide.Web.Models.StockDetail
{
    public class StockDetailImageViewModel
    {
        public string id { get; set; }
        public string part_no { get; set; }
        public string product_name { get; set; }
        public string description { get; set; }
        public string Selling_Price { get; set; }
        public string barcode_no { get; set; }
        public string barcodefile { get; set; }
        public string url { get; set; }
        public string product_image { get; set; }

        public List<StockImageInfo> lststockImages;
    }

    public class StockImageInfo 
    {
        public string id { get; set; }
        public string name { get; set; }
        public string image_filepath { get; set; }
        public string image_order { get; set; }
        public string status { get; set; }
        public string image_alt_text { get; set; }
    }

    public class DataTableDataImages
    {
        public int draw { get; set; }
        public int recordsTotal { get; set; }
        public int recordsFiltered { get; set; }
        public List<StockItemInfo> data { get; set; }
    }   
}

GoodSide.Web/Models/StockDetail/StockDetailSimilarProductsModel.cs
using GoodSide.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GoodSide.Web.Models.StockDetail
{
    public class StockDetailSimilarProductsModel
    {
        public List<StockProductInfo> lststockImages;
    }

    public class StockProductInfo 
    {
        public string productid { get; set; }
        public string product_name { get; set; }
        public string image_filepath { get; set; }
        public string image_alt_text { get; set; }
        public string total { get; set; }
    }

   
}

GoodSide.Web/Models/StockDetail/StockDetailViewModel.cs
using GoodSide.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GoodSide.Web.Models.StockDetail
{
    public class StockDetailViewModel
    {
        public string id { get; set; }
        public string part_no { get; set; }
        public string product_name { get; set; }
        public string description { get; set; }
        public string Selling_Price { get; set; }
        public string barcode_no { get; set; }
        public string barcodefile { get; set; }
        public string url { get; set; }
        public string product_image { get; set; }

        public List<StockAvailabilityInfo> lstStockAvailability;
    }

    public class StockAvailabilityInfo 
    {
        public string id { get; set; }
        public string name { get; set; }
        public string reference { get; set; }
        public string edate { get; set; }
        public string totalQty { get; set; }
        public string inorder { get; set; }
    }

    public class DataTableData
    {
        public int draw { get; set; }
        public int recordsTotal { get; set; }
        public int recordsFiltered { get; set; }
        public List<StockItemInfo> data { get; set; }
    }   
}

GoodSide.Web/Controllers/StockDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Data;

using System.Net;
using System.Net.Http;

using System.Web.Http;
using GoodSide.Domain.Entities;
using GoodSide.Domain.Services;
using GoodSide.Web.Models.StockDetail;
using AutoMapper;
namespace GoodSide.Web.Controllers
{
    public class StockDetailController : Controller
    {
        private IStockDetailService _stockDetailService;
        private IStockItemService _stockItemService;

        public StockDetailController(IStockDetailService stockDetailService, IStockItemService stockItemService)
        {
            _stockDetailService = stockDetailService;
            _stockItemService = stockItemService;
        }

        // GET: StockDetail
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetTableData(int draw, int start, int length)
        {
            var test = string.Empty;

            string search = " ";
            if (HttpContext.Request.QueryString["search[value]"] != null)
            {
                search = HttpContext.Request.QueryString["search[value]"]; ;
            }

            int sortColumn = -1;
            string sortDirection = "asc";

            if (HttpContext.Request.QueryString["order[0][column]"] != null)
            {
                sortColumn = int.Parse(HttpContext.Request.QueryString["order[0][column]"]);
            }
            if (HttpContext.Request.QueryString["order[0][dir]"] != null)
            {
                sortDirection = HttpContext.Request.QueryString["order[0][dir]"];
            }

            var lstProperties = typeof(StockItemInfo).GetProperties().ToList();

            //if (string.IsNullOrEmpty(search))
            //{
            //    search = "%%";
            //}
            //else
            //{
            //    search = "%" + search + "%";
            //}

            // search = HttpUtility.UrlEncode(search);
            var result = _stockItemService.GetAll(search.Trim(), start, length, lstProperties[sortColumn].Name, sortDirection);

            DataTableData dataTableData = new DataTableData();
            dataTableData.draw = draw;
            dataTableData.recordsTotal = result.pagingInfo.FirstOrDefault().t;
            dataTableData.data = result.stockItemInfo;
            dataTableData.recordsFiltered = result.pagingInfo.FirstOrDefault().t;
            foreach (var row in dataTableData.data)
            {
                if (row.onpromo == "x")
                    row.onpromo = row.onpromo.Replace("x", "YES");
                else
                    row.onpromo = row.onpromo.Replace("blank", "NO");
            }

            return Json(dataTableData, JsonRequestBehavior.AllowGet);
        }

        public ActionResult StockDetailedInfo(int stockId)
        {
            var result = _stockDetailService.GetStockDetailedInfo(stockId);

            StockDetailViewModel objModel = new StockDetailViewModel();

            Mapper.CreateMap<StockDetail, StockDetailViewModel>();

            objModel = Mapper.Map<StockDetail, StockDetailViewModel>(result.stockDetail[0]);

            Mapper.CreateMap<StockAvailabilityDetail, StockAvailabilityInfo>();

            objModel.lstStockAvailability = Mapper.Map<List<StockAvailabilityDetail>, List<StockAvailabilityInfo>>(result.stockAvailability);

            return PartialView("_StockDetailedInfo", objModel);
        }
        public ActionResult StockDetailedImageInfo(int stockId)
        {
            var result = _stockDetailService.GetStockImageInfo(stockId);

            StockDetailImageViewModel objModel = new StockDetailImageViewModel();

            Mapper.CreateMap<StockDetailImage, StockDetailImageViewModel>();

            if(result.stockDetail.Count>0)
                objModel = Mapper.Map<StockDetailImage, StockDetailImageViewModel>(result.stockDetail[0]);

            Mapper.CreateMap<StockDetailImageList, StockImageInfo>();

            objModel.lststockImages = Mapper.Map<List<StockDetailImageList>, List<StockImageInfo>>(result.stockImages);

            return PartialView("_StockDetailsImageInfo", objModel);
        }
        public PartialViewResult _StockDetails()
        {

            return PartialView();
        }




    }
}

GoodSide.Web/Views/StockDetail/CartDisplay.cshtml
@model List<GoodSide.Web.Models.StockDetail.CartItem>

<script src="@Url.Content("~/Scripts/custom/pos.js")"></script>
<style>
    .table-responsive td {
        padding: 5px !important;
    }

    .form-control-spinner {
        margin: 10px !important;
    }   
</style>

<div id="divallCartIteminfo">
    <h1 class="page-title">Shopping Cart</h1>
    <div id="grid">
        <div id="productlistscroll">
            <div class="form-group pull-right ">
                <button class="btn btn-primary" onclick="location.href='@Url.Action("Index", "StockDetail")'" type="button" id="btnAdd"><i class='fa fa-search'></i>BackToProduct</button>
            </div>
            <!-- Grid start -->
            <div class="table-responsive">
                <table id="tblProductDisplay" class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            @*  <th><input id="ckSelectAll" style="text-align:center !important " type="checkbox" class="checkbox" /></th>*@
                            <th>ProductID</th>
                            <th>Product Name</th>
                            <th>Price</th>
                            <th>QTY</th>
                            <th>ItemTotal</th>
                            <th>Remove Item</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            string textboxId = "txt" + "_" + item.ProductId;
                            string tdsalespriceId = "tdsalesprice" + "_" + item.ProductId;
                            string tditemtotalId = "tditemtotal" + "_" + item.ProductId;                         
                            <tr>
                                @* <td class="center-block"><input style="text-align:center !important " type="checkbox" class="checkbox chkProducts" data-id="@item.pid" data-uid="@item.uniqueid" /></td>*@
                                <td>@item.ProductId</td>
                                <td>@item.ProductName</td>
                                <td id='@tdsalespriceId'>@item.SalePrice</td>
                                <td>
                                    <div class="number-spinner">
                                        <table cellpadding="3">
                                            <tr>
                                                <td rowspan="2">@Html.TextBoxFor(m => item.Quantity, new { @class = "form-control text-center form-control-spinner", @maxlength = "3", @id = textboxId, @min = "0", @max = "1000", @style = "width:70px;height:40px", @type = "text" })</td>
                                                <td>
                                                    <div><button type="button" class="btn btn-default btn-info" data-dir="up" data-dir2='@tditemtotalId' data-dir1='@tdsalespriceId'><span class="glyphicon glyphicon-plus"></span></button></div>
                                                    <div class="top5"><button type="button" class="btn btn-default btn-info" data-dir2='@tditemtotalId' data-dir1='@tdsalespriceId' data-dir="dwn"><span class="glyphicon glyphicon-minus"></span></button></div>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </td>
                                <td id='@tditemtotalId'>@((item.SalePrice * item.Quantity))</td>
                                <td class="delete-control" onclick="deleteitem('@item.ProductId','@item.ItemId')"></td>

                            </tr>
                        }
                        @*@if (Model.orderdetailList.Count() == 0)
                            {
                                <tr>
                                    <td colspan="12">List of products searched by barcode above</td>
                                </tr>
                            }*@
                    </tbody>
                </table>
            </div>
            <div class="row">              
                    <div class="col-xs-12">
                        <h4>Order Total: <label style="font-size:18px" id="lblOrderTotal">@Model.Sum(x => x.Itemtotal)</label></h4>
                   </div>              
            </div>    
        </div>
        <div class="form-group pull-right ">
            <button class="btn btn-primary" type="button" onclick="AddItemstoQuotes()" id="btnSave"><i class='fa fa-search'></i>Save Order</button>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('divCartInfo').show();
    });

    function deleteitem(productid,itemid) {
        var actionURL = "@string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~/StockDetail/DeleteItem"))";
        data = { productid: productid , itemid : itemid }
        $.ajax({
            url: actionURL,
            data: data,
            type: "POST",
            datatype: "json",
            success: function (data) {
                result = data;
                if (result.success == true) {
                    POSJS.LoadCartDisplay();
                }
                else {

                }
            },
            error: function (xhr, status, error) {
                result = xhr.responseText;
            },
            complete: function () {

            }
        });
    }

    function AddItemstoQuotes() {
        try {
            var obj = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model));
            $.each(obj, function (i, v) {
                var productid = this.ProductId;
                var saleprice = this.SalePrice;
                var itemtotal = this.Itemtotal;
                var qty = parseInt($("#txt" + "_" + productid).val());
                this.Quantity = qty;
            });


            var dataResult = JSON.stringify({items : JSON.stringify(obj)});
            var partialViewUrl = "@string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~/StockDetail/SaveOrderasQuote"))";
                $.ajax({
                    url: partialViewUrl,
                    type: "POST",
                    data: dataResult,
                    contentType: "application/json; charset=utf-8",
                    success: function (resultData) {
                        if (resultData.success == true) {
                            BootstrapDialog.alert('New Generated OrderID: ' + resultData.orderId);

                            var urlAction ="@string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~/StockDetail/CreateNewOrder"))";                            
                            var result = POSJS.CreateNewOrder(urlAction);
                        
                            location.href='@Url.Action("Index", "StockDetail")';
                    }
                    else {
                        BootstrapDialog.alert(resultData.message);
                    }
                }
            });
        }
        catch (e) {
            alert(e);
        }
    }

    $(function () {
        var action;
        $(".number-spinner button").click(function () {
            btn = $(this);
            input = btn.closest('.number-spinner').find('input');
            btn.closest('.number-spinner').find('button').prop("disabled", false);          
            if (btn.attr('data-dir') == 'up') {

                //action = setInterval(function(){
                if (input.attr('max') == undefined || parseInt(input.val()) < parseInt(input.attr('max'))) {
                    var ValueBeforUpdate = parseInt(document.getElementById(btn.attr('data-dir1')).innerHTML) * (parseInt(input.val()));
                    input.val(parseInt(input.val()) + 1);
                    var ValueAfterUpdate = parseInt(document.getElementById(btn.attr('data-dir1')).innerHTML) * (parseInt(input.val()));
                    document.getElementById(btn.attr('data-dir2')).innerHTML = ValueAfterUpdate ;                  
                    document.getElementById("lblOrderTotal").innerHTML = (parseInt(document.getElementById("lblOrderTotal").innerHTML) + (ValueAfterUpdate - ValueBeforUpdate));
                } else {
                    btn.prop("disabled", true);
                    clearInterval(action);
                }
                // }, 70);

            } else {
                //action = setInterval(function(){
                if (input.attr('min') == undefined || parseInt(input.val()) > parseInt(input.attr('min'))) {
                    var ValueBeforUpdate = parseInt(document.getElementById(btn.attr('data-dir1')).innerHTML) * (parseInt(input.val()));                 
                    input.val(parseInt(input.val()) - 1);
                    var ValueAfterUpdate = parseInt(document.getElementById(btn.attr('data-dir1')).innerHTML) * (parseInt(input.val()));                 
                    document.getElementById(btn.attr('data-dir2')).innerHTML = ValueAfterUpdate ;                  
                    document.getElementById("lblOrderTotal").innerHTML = (parseInt(document.getElementById("lblOrderTotal").innerHTML) - (ValueBeforUpdate - ValueAfterUpdate));
                } else {
                    btn.prop("disabled", true);
                    clearInterval(action);
                }
                //}, 70);
            }
        });
    });

    function BackToProduct()
    {

    }

</script>

GoodSide.Web/Views/StockDetail/Index.cshtml

@{
    ViewBag.Title = "StockManagement";
    Layout = "~/Views/Shared/_UboldLayout.cshtml";
}
@section additionalCSS {
    @Styles.Render("~/Content/DataTableCSS")
}

<style type="text/css">
    td.details-control {
        background: url(@Url.Content("~/Content/ubold/images/details_open.png")) no-repeat center center;
        cursor: pointer;
    }

    tr.shown td.details-control {
     background: url(@Url.Content("~/Content/ubold/images/details_close.png")) no-repeat center center;
    }


</style>


<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">Stock Maintenance</h4>
        <ol class="breadcrumb">
            <li>
                <a href="#">Stock Details</a>
            </li>
            <li>
                <a href="#">Stock Maintenance</a>
            </li>
            <li class="active">
                Stock Items
            </li>
        </ol>

    </div>
</div>
<!-- Page-Title -->




<div class="row">
    <div class="col-sm-12">
        <div class="card-box table-responsive">
            <h4 class="m-t-0 header-title"><b>Stock list</b></h4>
            <p class="text-muted font-13 m-b-30">

            </p>

            <table id="datatable" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Details</th>
                        <th>Part No</th>
                        <th>Product Name</th>
                        <th>Supplier</th>
                        <th>Category</th>
                        <th>Type</th>
                        <th>Description</th>
                        <th>Barcode</th>
                        <th>Was Price</th>
                        <th>Sell Price</th>
                        <th>On Promotion</th>
                        <th>T.</th>
                        <th>A.</th>
                        <th>U.</th>
                        <th>PO</th>
                    </tr>
                </thead>


                @*<tbody>
                        <tr>
                            <td>Tiger Nixon</td>
                            <td>System Architect</td>
                            <td>Edinburgh</td>
                            <td>61</td>
                            <td>2011/04/25</td>
                            <td>$320,800</td>
                        </tr>
                    </tbody>*@
            </table>
        </div>
    </div>
</div>

@section Scripts {

    @Scripts.Render("~/bundles/jquery")

    <script src="~/Content/ubold/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/ubold/plugins/datatables/dataTables.bootstrap.js"></script>
    <script src="~/Content/ubold/plugins/datatables/dataTables.responsive.min.js"></script>
    <script src="~/Content/ubold/pages/datatables.init.js"></script>
    <script type="text/javascript">
        var table;
        var htmlResult;
        $(function () {
            var oTable = $('#datatable').dataTable({
                "processing": true,
                "serverSide": true,
                "info": true,
                "stateSave": true,
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                "ajax": {
                    "url": "@string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"))/StockDetail/GetTableData",
                    "type": "GET"
                },
                "columns": [
                     {
                         "class": "details-control",
                         "orderable": false,
                         "data": null,
                         "defaultContent": ""
                     },
                    { "data": "part_no", "orderable": true },
                    { "data": "product_name", "orderable": true },
                    { "data": "supplier", "orderable": true },
                    { "data": "categoryid", "orderable": false },
                    { "data": "typeid", "orderable": false },
                    { "data": "description", "orderable": false },
                    { "data": "barcode_no", "orderable": false },
                    { "data": "spnow", "orderable": true },
                    { "data": "sellingprice", "orderable": true },
                    { "data": "onpromo", "orderable": false },
                    { "data": "physicalstocklevel", "orderable": false },
                    { "data": "allocatedstocklevel", "orderable": false },
                    { "data": "unallocatedstocklevel", "orderable": false },
                    { "data": "inorder", "orderable": false }

                ],
                "order": [[9, "asc"]]
            });

            oTable.fnSort([[1, 'asc']]);

            table = oTable.DataTable();

        });

        /* Formatting function for row details - modify as you need */
        function format(d) {

            var result = "";
            var url = "@string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"))StockDetail/StockDetailedInfo";
            $.ajax({
                "url": url,
                dataType: 'html',
                data: { stockId: d.id },
                cache: false,
                async: false,
                type: "GET",
                success: function (resultData) {
                    result = resultData;
                },
                error: function (xhr, status, error) {
                    console.log(xhr.responseText);
                }
            });
            return result;
        }

        // Add event listener for opening and closing details
        $('#datatable').on('click', 'td.details-control', function () {
            var tr = $(this).closest('tr');
            var row = table.row(tr);

            if (row.child.isShown()) {
                // This row is already open - close it
                row.child.hide();
                tr.removeClass('shown');
            } else {
                // Open this row
                var url = "@string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"))StockDetail/StockManagement/StockDetailedInfo";

                var htmlResult = format(row.data());
                row.child(htmlResult).show();
                tr.addClass('shown');
            }
        });




    </script>
}

GoodSide.Web/Views/StockDetail/_StockDetailedInfo.cshtml
@model  GoodSide.Web.Models.StockDetail.StockDetailViewModel
<div class="table-responsive" id="childTableContainer">

    <table id="mainTable" class="table table-striped m-b-0">
        <thead>
            <tr>
                <th>Id</th>
                <th>Location</th>
                <th>Container</th>
                <th>Arrival Date</th>
                <th>Available</th>
                <th>In Temp Order(s)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var objAvailInfo in Model.lstStockAvailability)
            {
                <tr>
                    <td>@objAvailInfo.id</td>
                    <td>@objAvailInfo.name</td>
                    <td>@objAvailInfo.reference</td>
                    <td>@objAvailInfo.edate</td>
                    <td>@objAvailInfo.totalQty</td>
                    <td>@objAvailInfo.inorder</td>
                </tr>
            }
        </tbody>
    </table>

    <table id="mainTable" class="table table-striped m-b-0">
        <tbody>
            <tr>
                <td class="col-md-3">
                    Product Name
                </td>
                <td class="col-md-3">
                    @Model.product_name
                </td>
            </tr>
            <tr>
                <td>
                    Description
                </td>
                <td>
                    @Model.description
                </td>
            </tr>
            <tr>
                <td>
                    Selling Price
                </td>
                <td>
                    @Model.Selling_Price
                </td>
            </tr>
            <tr>
                <td>
                    Barcode
                </td>
                <td>
                    @Model.barcode_no
                </td>
            </tr>
            <tr>
                <td>
                    Barcode Image
                </td>
                <td>
                    <img src="@Model.barcodefile" alt="Barcode Image" />
                </td>
            </tr>
            <tr>
                <td>
                    Website Link
                </td>
                <td>
                    @Model.url
                </td>
            </tr>
            <tr>
                <td>
                    Product Image
                </td>
                <td>
                    <img src="@Model.product_image" alt="Product Image" />
                </td>
            </tr>
        </tbody>
    </table>
</div>